### ISSUE TITLE
Question about data preparing.

### ISSUE THREAD

**Issue by Adenialzz** [fkodom/clip-text-decoder#13]
Why the acquisition of image data is implemented in the form of network io instead of processing local images.

**Comment by Adenialzz** [comment]
I guess maybe that's because then we can just load the web image, extract the features using the image encoder and save the features, instead of saving the images ?

**Comment by fkodom** [comment]
@Adenialzz Yep, you're right about saving the features, rather than the original images.  In `train.py`, the CLIP/BLIP vision backbone is left frozen, and we only train the language model head.  It's **much** faster if we only compute the image embeddings once, and then load them as needed for training.

As for the network I/O part -- the [build_cached_dataset](https://github.com/fkodom/clip-text-decoder/blob/e52eb7fd8b8f94b12ea446704599377dcc367379/clip_text_decoder/dataset.py#L59) function is agnostic about where the data is stored:

```python
def build_cached_dataset(
    data_iterable: Iterable[Image.Image, Any],
    vision_backbone: str,
) -> CachedDataset:
    print("Compiling encodings with text captions...")
    pipe = IterableWrapper(iter(data_iterable))
    pipe = pipe.batch(32)
    pipe = ParallelImageEncoder(pipe, vision_backbone=vision_backbone)
    pipe = pipe.unbatch()

    data = [(encoding, captions) for encoding, captions in tqdm(pipe)]
    return CachedDataset(data=data)
```

^^ It just accepts an `Iterable` object.  That could be a local dataset, or as I implemented it for COCO Captions, a collections of URLs pointing to remote files.  It seemed least intrusive to stream the images, rather than require users to download and store them in a particular directory.

**Comment by Adenialzz** [comment]
@fkodom Thank you for your reply. The reason I'm asking this question is that in my area, the network is often unstable. Now I have downloaded the coco caption dataset and implemented feature extraction and saving locally. Then use your training script to train.

Another problem I've had recently with your training script is that the gpu memory usage during training often keeps increasing, eventually causing oom error. When I usually use native pytorch to build training scripts, the memory usage is fixed. What do you think this might be caused by?

**Comment by fkodom** [comment]
Not sure about the GPU memory — it’s stable during my runs.  I’d check the installed `torch` and `pytorch-lightning` versions, and make sure you’ve got the latest patch versions.  Otherwise, I don’t know what could be causing that.

The image features should be cached (and downloaded from GDrive) for the BLIP and CLIP (ViT-B/32) backbones.  In those cases, you should only be downloading <200 MB.  Is there a reason you need to rebuild the cache locally?

**Comment by Adenialzz** [comment]
The reason why I rebuild data locally is that I want to use larger CLIP image encoder (like ViT-L/14@336px) features to train an image captioning model. And do some experiments (like #10 ) with the corresponding CLIP text encoder.

Actually, when I use the pkl file you provide, the problem of oom will also occur. I have checked git history of my local code and found no difference with this repo. Maybe I should debug again carefully.

Anyways, thanks for your advice.
